dbConfig:
  database: unleash
  host: postgresql.postgresql
  pass: Password
  port: 5432
  user: admin
  ssl: false

fullnameOverride: ""

image:
  repository: unleashorg/unleash-server
  tag: 4.4.4
  pullPolicy: Always

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  hosts:
    - host: unleash.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
       - unleash.example.com
      secretName: tls-unleash


replicaCount: 1

postgresql:
  enabled: false
